#background_opacity: 0.6

# Colors (Pencil Light)
# https://github.com/eendroroy/alacritty-theme/blob/master/themes/pencil_light.yaml
colors:
  # Default Colors
  primary:
    background: '0xf1f1f1'
    foreground: '0x424242'
  # Normal colors
  normal:
    black:   '0x212121'
    red:     '0xc30771'
    green:   '0x10a778'
    yellow:  '0xa89c14'
    blue:    '0x008ec4'
    magenta: '0x523c79'
    cyan:    '0x20a5ba'
    white:   '0xe0e0e0'
  # Bright colors
  bright:
    black:   '0x212121'
    red:     '0xfb007a'
    green:   '0x5fd7af'
    yellow:  '0xf3e430'
    blue:    '0x20bbfc'
    magenta: '0x6855de'
    cyan:    '0x4fb8cc'
    white:   '0xf1f1f1'

font:
    size: 14
    #use_thin_strokes: true

key_bindings:
    - { key: B, mods: Alt, chars: "\x1bb" }
    - { key: F, mods: Alt, chars: "\x1bf" }
    - { key: L, mods: Command, action: ClearHistory }
    - { key: N, mods: Command, action: SpawnNewInstance }
    - { key: C, mods: Shift|Control, action: Copy }
    - { key: V, mods: Shift|Control, action: Paste }

mouse:
    hide_when_typing: true

selection:
  semantic_escape_chars: "\t !\"#%&'()*+,-./:;<=>?@[\\]^`{|}~"

shell:
  program: /usr/local/bin/bash
  args:
    - --login

window:
    dimensions:
        columns: 80
        lines: 25
    #decorations: buttonless
    #decorations: none
