alias act='source .venv/bin/activate'
alias c='cd "$(picode)"'
alias cdk='npx --package aws-cdk cdk'
alias codex='npx --package @openai/codex codex'
alias cpx='cp -i'
alias datex='date -u +%Y-%m-%dT%H:%M:%SZ'
alias deact=deactivate
alias fo='sed "s/   */,/g"|vd --filetype=csv'
alias gai='git add --interactive'
alias gdf='git difftool'
alias gemini='npx @google/gemini-cli'
alias gla='git ls-files --others --exclude-standard'
alias glf='git ls-files'
alias gls='GIT_PAGER=cat git diff --name-only --cached'
alias ifx='perl -MIO::Socket::INET -e '\''my $s=IO::Socket::INET->new(Proto=>"udp",PeerAddr=>"8.8.8.8",PeerPort=>53);print $s->sockhost,"\n"'\'''
alias jl='/usr/libexec/java_home --verbose'
alias jo='python3 -m json.tool|less'
alias jqs='jq .scripts package.json'
alias k=kubectl
alias kj='kubectl --output json'
alias kk='$(pickube)'
alias mvx='mv -i'
alias na='npm run --if-present lint && npm run --if-present format && npm run --if-present build'
alias ng='npx --package @angular/cli ng'
alias nr='npm run'
alias nsx='lsof -P -iTCP -n -sTCP:LISTEN'
alias po='npx pino-pretty --colorize --translateTime "UTC:yyyy-mm-dd'"'"'T'"'"'HH:MM:ss'"'"'Z'"'"'"|less -R;reset'
alias psx='ps -A -o user,pid,ppid,command'
alias rmx='rm -i'
alias sedi='perl -pi -e'
alias sm='alacritty --option font.size=10 --option window.dimensions.lines=80 &'
alias t='cd "$(picode Documents)"'
alias v=nvim
alias vim=nvim
alias vimdiff='nvim -d'
alias vimx='whence -p vim && $(whence -p vim)'

if [ $(uname) = Darwin ]; then
    alias ssh='ssh -o "XAuthLocation=/opt/X11/bin/xauth"'
fi
